#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaViajes
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PROYECTO")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void InsertVIAJES(VIAJES instance);
    partial void UpdateVIAJES(VIAJES instance);
    partial void DeleteVIAJES(VIAJES instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::AgenciaViajes.Properties.Settings.Default.PROYECTOConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTE
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<VIAJES> VIAJES
		{
			get
			{
				return this.GetTable<VIAJES>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTE")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Viaje;
		
		private string _NombreApell;
		
		private string _Destino;
		
		private System.Nullable<System.DateTime> _FechaSalida;
		
		private System.Nullable<System.DateTime> _FechaVuelta;
		
		private System.Nullable<decimal> _Satisfacion;
		
		private string _Sexo;
		
		private string _Discapacidad;
		
		private string _Descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnViajeChanging(string value);
    partial void OnViajeChanged();
    partial void OnNombreApellChanging(string value);
    partial void OnNombreApellChanged();
    partial void OnDestinoChanging(string value);
    partial void OnDestinoChanged();
    partial void OnFechaSalidaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaSalidaChanged();
    partial void OnFechaVueltaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVueltaChanged();
    partial void OnSatisfacionChanging(System.Nullable<decimal> value);
    partial void OnSatisfacionChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnDiscapacidadChanging(string value);
    partial void OnDiscapacidadChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public CLIENTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Viaje", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Viaje
		{
			get
			{
				return this._Viaje;
			}
			set
			{
				if ((this._Viaje != value))
				{
					this.OnViajeChanging(value);
					this.SendPropertyChanging();
					this._Viaje = value;
					this.SendPropertyChanged("Viaje");
					this.OnViajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreApell", DbType="VarChar(100)")]
		public string NombreApell
		{
			get
			{
				return this._NombreApell;
			}
			set
			{
				if ((this._NombreApell != value))
				{
					this.OnNombreApellChanging(value);
					this.SendPropertyChanging();
					this._NombreApell = value;
					this.SendPropertyChanged("NombreApell");
					this.OnNombreApellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(100)")]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this.OnDestinoChanging(value);
					this.SendPropertyChanging();
					this._Destino = value;
					this.SendPropertyChanged("Destino");
					this.OnDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida", DbType="Date")]
		public System.Nullable<System.DateTime> FechaSalida
		{
			get
			{
				return this._FechaSalida;
			}
			set
			{
				if ((this._FechaSalida != value))
				{
					this.OnFechaSalidaChanging(value);
					this.SendPropertyChanging();
					this._FechaSalida = value;
					this.SendPropertyChanged("FechaSalida");
					this.OnFechaSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVuelta", DbType="Date")]
		public System.Nullable<System.DateTime> FechaVuelta
		{
			get
			{
				return this._FechaVuelta;
			}
			set
			{
				if ((this._FechaVuelta != value))
				{
					this.OnFechaVueltaChanging(value);
					this.SendPropertyChanging();
					this._FechaVuelta = value;
					this.SendPropertyChanged("FechaVuelta");
					this.OnFechaVueltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Satisfacion", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Satisfacion
		{
			get
			{
				return this._Satisfacion;
			}
			set
			{
				if ((this._Satisfacion != value))
				{
					this.OnSatisfacionChanging(value);
					this.SendPropertyChanging();
					this._Satisfacion = value;
					this.SendPropertyChanged("Satisfacion");
					this.OnSatisfacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(10)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discapacidad", DbType="VarChar(20)")]
		public string Discapacidad
		{
			get
			{
				return this._Discapacidad;
			}
			set
			{
				if ((this._Discapacidad != value))
				{
					this.OnDiscapacidadChanging(value);
					this.SendPropertyChanging();
					this._Discapacidad = value;
					this.SendPropertyChanged("Discapacidad");
					this.OnDiscapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(400)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIAJES")]
	public partial class VIAJES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdViaje;
		
		private string _Usuario;
		
		private string _Destino;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<decimal> _NivelSatisfacion;
		
		private string _Sexo;
		
		private string _Discapacidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdViajeChanging(string value);
    partial void OnIdViajeChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnDestinoChanging(string value);
    partial void OnDestinoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnNivelSatisfacionChanging(System.Nullable<decimal> value);
    partial void OnNivelSatisfacionChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnDiscapacidadChanging(string value);
    partial void OnDiscapacidadChanged();
    #endregion
		
		public VIAJES()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdViaje", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdViaje
		{
			get
			{
				return this._IdViaje;
			}
			set
			{
				if ((this._IdViaje != value))
				{
					this.OnIdViajeChanging(value);
					this.SendPropertyChanging();
					this._IdViaje = value;
					this.SendPropertyChanged("IdViaje");
					this.OnIdViajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(10)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(100)")]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this.OnDestinoChanging(value);
					this.SendPropertyChanging();
					this._Destino = value;
					this.SendPropertyChanged("Destino");
					this.OnDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelSatisfacion", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> NivelSatisfacion
		{
			get
			{
				return this._NivelSatisfacion;
			}
			set
			{
				if ((this._NivelSatisfacion != value))
				{
					this.OnNivelSatisfacionChanging(value);
					this.SendPropertyChanging();
					this._NivelSatisfacion = value;
					this.SendPropertyChanged("NivelSatisfacion");
					this.OnNivelSatisfacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(10)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discapacidad", DbType="VarChar(20)")]
		public string Discapacidad
		{
			get
			{
				return this._Discapacidad;
			}
			set
			{
				if ((this._Discapacidad != value))
				{
					this.OnDiscapacidadChanging(value);
					this.SendPropertyChanging();
					this._Discapacidad = value;
					this.SendPropertyChanged("Discapacidad");
					this.OnDiscapacidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
